### ISSUE TITLE
R version 3.5.0

### ISSUE THREAD

**Issue by koen-venema2** [nhanhocu/metamicrobiomeR#1]
Sorry for not being an IT wizz, but I run R 3.5.0 in RStudio, and the unpon trying to install the package the program tells me ‘metamicrobiomeR’ is not available (for R version 3.5.0), but the Description file says "Depends: R (>= 3.4.2)".
What am I missing??

**Comment by nhanhocu** [comment]
Hi,
Sorry that I have not been active on github recently and to give you a prompt response. 
Did you follow the installation tutorial? Can you copy the steps/codes you did and the corresponding error messages? 
Many thanks,
Nhan 
PS: you need to install "devtools" before installing the package "metamicrobiomeR" from github, and your computer need internet access.  
rm(list=ls()) # clear all
install.packages("devtools") 
library(devtools)
#install and load package metamicrobiomeR
install_github("nhanhocu/metamicrobiomeR")
library(metamicrobiomeR)

**Comment by theo-allnutt-bioinformatics** [comment]
I also got multiple errors (many pages) on installation, saying packages not available for metamicrobiomeR.

**Comment by theo-allnutt-bioinformatics** [comment]
Devtools was installed.

**Comment by nhanhocu** [comment]
Hi, 
Please update your R to most recent version and you should be able to to install the package "metamicrobiomeR". My R version is 3.5.1 and it worked (same for R 6.0). Sorry I will update the DESCRIPTION file.
