### ISSUE TITLE
GAMLSS family BEZI after zero replacement and CLR transformation

### ISSUE THREAD

**Issue by Nick243** [nhanhocu/metamicrobiomeR#10]
Hi Nhan,

Thanks for developing the approaches and user-friendly functions in the metamicrobiomeR package. This is quite impressive! 

I have a question on the appropriate probability distribution to use in GAMLSS for relative abundance estimation and testing after zero replacement and CLR transformation.  After the replacement and transformation, would I expect to have few/no zeros and negative values? If so, would you still recommend using the BEZI family? Or would you then perhaps recommend also using propmed.rel = "lm" in the taxa.compare function (or fitting the model in GAMLSS assuming a different distribution for the response)?

Thanks in advance for any thoughts on the matter!

Nick

**Comment by nhanhocu** [comment]
Dear Nick,
Thanks for your interest in the package. You are right that if you do CLR transformation, you should use "lm". 
Bests,
Nhan
