### ISSUE TITLE
Meta analysis for single group?

### ISSUE THREAD

**Issue by valery-shap** [nhanhocu/metamicrobiomeR#20]
Hello, 
Thank you for the useful package!
I have a question about appropriate data for it. 
All the examples are about comparing two groups that are preset in each paper.
But I have a bit different task.
For example, I have 10 papers with the data(mean relative abundance) of one group and 20 papers with the data for another group. And I’d like to compare them.
Could I use the package for this type of analysis?

Best regards, 
Valery

**Comment by nhanhocu** [comment]
Hi,
 Sorry for late reply. 
I guess the package is not designed for the task you mentioned in term of meta-analysis. However, if only for comparison between two groups using GAMLSS, you can try pooling data from all studies and do the comparison. 
Bests,
Nhan

**Comment by valery-shap** [comment]
Hello,
thank you for reply! do you mean that one package: https://www.gamlss.com/? Could you advice the function for this goal?
Best regards,
Valery
